# if randomGeneration is set to 'true' the plugin will either generate a random alphanumeric, or alphabetical string if alphanumeric is set to 'true' or 'false'
# the length is the length of the randomly generated alphanumeric, or alphabetical string.
# if randomGeneration is set to 'false' the plugin will select a random word from the wordList for the captcha test
# You have to set either chat to 'true', commands to 'true', or both to 'true'. if they are both set to 'false', the plugin will disable itself.
captcha:
  randomGeneration: true
  alphanumric: true
  length: 6
  wordList:
  - Bob
  - Joe
  - Jack
  - Humanoid
captha-required:
  chat: true
  commands: true
